name: MLOps CICD
on:
  push:
    branches: [main]
    # paths:
    # - '*.ipynb'
  
env:
  GCS_SOURCE: "thermal-imprint-425305-u1-source-bucket"
  GCS_OUTPUT: "thermal-imprint-425305-u1-output-bucket"
  
jobs:
  jupyter-notebook-cicd:
    name:  Jupyter Notebook CICD 
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs: 
      notebook_files: ${{ steps.getnotebooks.outputs.notebook_files }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      # - name: Fetch Updated Jupyter Notebooks
      #   id: getnotebooks        
      #   run: |
      #     echo "Printing GitHub SHA: $GITHUB_SHA"
      #     echo "UPDATED_FILES=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA)" >> $GITHUB_ENV
      #     echo "Listing updated files: ${{ env.UPDATED_FILES }}"
      #     echo "UPDATED_NOTEBOOKS=$(echo $updated_files | grep -i '\.ipynb$')" >> $GITHUB_ENV
      #     echo "Listing updated notebooks: ${{ env.UPDATED_NOTEBOOKS }}"

      - name: Fetch Updated Jupyter Notebooks
        id: getnotebooks        
        run: |
          set +x
          echo "Printing GitHub SHA: $GITHUB_SHA"

        # Use variable to hold the command output temporarily
          updated_files=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA)

        # Save to GITHUB_ENV, replace newline with spaces for better handling
          echo "UPDATED_FILES=$(echo $updated_files | tr '\n' ' ')" >> $GITHUB_ENV

        # Add a newline for separation and clarity
      - name: Use Updated Files
        run: |
          echo "Listing updated files: $UPDATED_FILES"
          updated_notebooks=$(echo $UPDATED_FILES | grep -i '\.ipynb$')

        # Again, saving the output environment variable
          echo "UPDATED_NOTEBOOKS=$(echo $updated_notebooks | tr '\n' ' ')" >> $GITHUB_ENV

      - name: List Updated Notebooks
        run: |
          echo "Listing updated notebooks: $UPDATED_NOTEBOOKS"
          
         
      # - name: Print Updated Jupyter Notebooks    
      #   run: |
      #     echo 'Updated Notebooks Output :${{ needs.getnotebooks.outputs.notebook_files }}'
      #     echo 'Updated Notebooks Env Var :${{ env.notebook_files_env }}'
          
      # - name: Execute Jupyter Notebook on Vertex AI
      #   id: notebook-review
      #   uses: google-github-actions/run-vertexai-notebook@v0
      #   with:
      #       gcs_source_bucket: '${{ env.GCS_SOURCE }}'
      #       gcs_output_bucket: '${{ env.GCS_OUTPUT }}'
      #       allowlist: '${{ needs.getnotebooks.outputs.notebook_files }}'

      # - name: Run Jupyter Notebooks
      #   run: |
      #     for i in ${{ steps.getfile.outputs.files }}
      #     do
      #         echo 'Running $i in AI Platform Training'
      #         gcloud-notebook-training --input-notebook $i  --project-id ${{ secrets.PROJECT_ID }}            
      #     done
