name: MLOps CICD
on:
  push:
    branches: [main]
    # paths:
    # - '*.ipynb'
  
env:
  GCS_SOURCE: "vocal-partition-435815-p8-source-bucket"
  GCS_OUTPUT: "vocal-partition-435815-p8-output-bucket"
  
jobs:
  jupyter-notebook-cicd:
    name:  Jupyter Notebook CICD 
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs: 
      notebook_files: ${{ steps.getnotebooks.outputs.notebook_files }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Set up gcloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Identify Modified Files
        run: |
          echo "Checking for Modified Files..."
          set +e  # Do not exit immediately on error
          
          # Identify modified Jupyter Notebooks
          CHANGED_NOTEBOOKS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^src/.*\.ipynb$')
          echo "$CHANGED_NOTEBOOKS" > changed_notebook.txt
          if [ -s changed_notebook.txt ]; then
            echo "Modified Jupyter Notebooks:"
            cat changed_notebook.txt
          else
            echo "No Jupyter notebooks have been modified."
          fi
          
          # Identify modified datasets
          CHANGED_DATASETS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^dataset/.*\.csv$')
          echo "$CHANGED_DATASETS" > changed_dataset.txt
          if [ -s changed_dataset.txt ]; then
            echo "Modified Datasets:"
            cat changed_dataset.txt
          else
            echo "No datasets have been modified."
          fi
          set -e  # Turn back on "exit immediately"
      
      - name: Upload Modified Files to GCS
        run: |
          # Upload modified datasets
          if [ -s changed_dataset.txt ]; then
            while IFS= read -r dataset; do
              echo "Uploading $dataset to GCS..."
              gsutil cp $dataset gs://${GCS_SOURCE}/dataset/
            done < changed_dataset.txt
            echo "Successfully uploaded all modified datasets."
          else
            echo "No datasets to upload or the file is empty."
          fi

          # Assuming a similar step for Jupyter notebooks
          if [ -s changed_notebook.txt ]; then
            while IFS= read -r notebook; do
              echo "Uploading $notebook to GCS..."
              gsutil cp $notebook gs://${GCS_SOURCE}/src/
            done < changed_notebook.txt
            echo "Successfully uploaded all modified notebooks."
          else
            echo "No Jupyter notebooks to upload or the file is empty."
          fiupyter notebooks to upload."
                fi

          
      # - name: Execute Jupyter Notebook on Vertex AI
      #   id: notebook-review
      #   uses: google-github-actions/run-vertexai-notebook@v0
      #   with:
      #       gcs_source_bucket: '${{ env.GCS_SOURCE }}'
      #       gcs_output_bucket: '${{ env.GCS_OUTPUT }}'
      #       allowlist: '${{ needs.getnotebooks.outputs.notebook_files }}'
