name: MLOps CICD
on:
  push:
    branches: [main]
    # paths:
    # - '*.ipynb'
  
env:
  GCS_SOURCE: "thermal-imprint-425305-u1-source-bucket"
  GCS_OUTPUT: "thermal-imprint-425305-u1-output-bucket"
  
jobs:
  jupyter-notebook-cicd:
    name:  Jupyter Notebook CICD 
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs: 
      notebook_files: ${{ steps.getnotebooks.outputs.notebook_files }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      
      - name: Identify Modified Jupyter Notebooks
        run: |
          set +e  # Do not exit immediately on error
          CHANGED_NOTEBOOKS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.ipynb$')
          set -e  # Turn back on exit immediately

          if [ -z "$CHANGED_NOTEBOOKS" ]; then
            echo "No Jupyter notebooks have been modified in this push."
          else
            echo "Modified Jupyter notebooks in this push:"
            echo "$CHANGED_NOTEBOOKS"
          fi

          echo "changed_notebooks=$CHANGED_NOTEBOOKS" >> $GITHUB_ENV

      # - name: Execute Jupyter Notebook on Vertex AI
      #   id: notebook-review
      #   uses: google-github-actions/run-vertexai-notebook@v0
      #   with:
      #       gcs_source_bucket: '${{ env.GCS_SOURCE }}'
      #       gcs_output_bucket: '${{ env.GCS_OUTPUT }}'
      #       allowlist: '${{ needs.getnotebooks.outputs.notebook_files }}'
