name: MLOps CICD
on:
  push:
    branches: [main]
    # paths:
    # - '*.ipynb'
  
env:
  GCS_SOURCE: "vocal-partition-435815-p8-source-bucket"
  GCS_OUTPUT: "vocal-partition-435815-p8-output-bucket"
  
jobs:
  jupyter-notebook-cicd:
    name:  Jupyter Notebook CICD 
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs: 
      notebook_files: ${{ steps.getnotebooks.outputs.notebook_files }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Set up gcloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Identify Modified Jupyter Notebooks
        run: |
          set +e  # Do not exit immediately on error
          CHANGED_NOTEBOOKS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.ipynb$')
          set -e  # Turn back on exit immediately
          if [ -z "$CHANGED_NOTEBOOKS" ]; then
            echo "No Jupyter notebooks have been modified in this push."
          else
            echo "Modified Jupyter notebooks in this push:"
            echo "$CHANGED_NOTEBOOKS"
            echo "$CHANGED_NOTEBOOKS" >> changed_notebook.txt
          fi
          CHANGED_DATASET=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.csv$')
          set -e  # Turn back on exit immediately
          if [ -z "$CHANGED_DATASET" ]; then
            echo "No Datasets have been modified in this push."
          else
            echo "Modified Datasets  in this push:"
            echo "$CHANGED_DATASET"
            echo "$CHANGED_DATASET" >> changed_dataset.txt
          fi
      
      - name: Upload Dataset and Source Code to GCS Bucket
        run: |
            
            DATASET="changed_dataset.txt"
            if [[ -f "$DATASET" ]]; then
              while IFS= read -r line; do
                  export CURRENT_DATASET="$line"
                  echo "Processing: $CURRENT_DATASET"
                  gsutil cp ../dataset/$CURRENT_DATASET gs://${{ env.GCS_SOURCE }}/dataset/  
              done < "$FILE"  

            else
              echo "Error: File does not exist."
            fi

            echo "Successfully uploaded Source Code ..."
            echo "Uploading Dataset ..."
            cd  ${GITHUB_WORKSPACE}/dataset/  
            gsutil cp ../dataset/*.csv gs://${{ env.GCS_SOURCE }}/dataset/
            echo "Successfully uploaded Dataset ..."
            echo "Uploading Source Code (Jupyter Notebook) ..."
            
            FILE="changed_notebook.txt"
            if [[ -f "$FILE" ]]; then
              while IFS= read -r line; do
                  export CURRENT_LINE="$line"
                  echo "Processing: $CURRENT_LINE"
                  gsutil cp ../src/$CURRENT_LINE gs://${{ env.GCS_SOURCE }}/src/  
              done < "$FILE"  

            else
              echo "Error: File does not exist."
            fi
            echo "Successfully uploaded Source Code ..."

      # - name: Execute Jupyter Notebook on Vertex AI
      #   id: notebook-review
      #   uses: google-github-actions/run-vertexai-notebook@v0
      #   with:
      #       gcs_source_bucket: '${{ env.GCS_SOURCE }}'
      #       gcs_output_bucket: '${{ env.GCS_OUTPUT }}'
      #       allowlist: '${{ needs.getnotebooks.outputs.notebook_files }}'
