name: MLOps CICD
on:
  push:
    branches: [main]
    # paths:
    # - '*.ipynb'
  
env:
  GCS_SOURCE: "thermal-imprint-425305-u1-source-bucket"
  GCS_OUTPUT: "thermal-imprint-425305-u1-output-bucket"
  
jobs:
  jupyter-notebook-cicd:
    name:  Jupyter Notebook CICD 
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs: 
      notebook_files: ${{ steps.getnotebooks.outputs.notebook_files }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Fetch Updated Jupyter Notebooks
        id: getnotebooks        
        run: |
          echo "Printing changed files "
          git diff-tree --no-commit-id --name-only -r $GITHUB_SHA | 
          echo "Setting up gha env var"
          echo "notebook_files=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA | grep -i .ipynb | xargs)" >> $GITHUB_ENV
          #echo "notebook_files=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA | grep -i .ipynb | xargs)" >> $GITHUB_OUTPUT
          #echo "notebook_files_env=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA | grep -i .ipynb | xargs)" >> $GITHUB_ENV
         
      - name: Print Updated Jupyter Notebooks    
        run: |
          #echo 'Updated Notebooks Output :${{ needs.getnotebooks.outputs.notebook_files }}'
          echo 'Updated Notebooks Env Var :${{ env.notebook_files }}'
          
      # - name: Execute Jupyter Notebook on Vertex AI
      #   id: notebook-review
      #   uses: google-github-actions/run-vertexai-notebook@v0
      #   with:
      #       gcs_source_bucket: '${{ env.GCS_SOURCE }}'
      #       gcs_output_bucket: '${{ env.GCS_OUTPUT }}'
      #       allowlist: '${{ needs.getnotebooks.outputs.notebook_files }}'

      # - name: Run Jupyter Notebooks
      #   run: |
      #     for i in ${{ steps.getfile.outputs.files }}
      #     do
      #         echo 'Running $i in AI Platform Training'
      #         gcloud-notebook-training --input-notebook $i  --project-id ${{ secrets.PROJECT_ID }}            
      #     done
